baseURL = "http://kodindonesia.com/"
languageCode = "en-us"
title = "Kodindonesia"
theme = "ananke"

DefaultContentLanguage = "en"


[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  favicon = ""
  site_logo = ""
  description = "Puzzles, games, ... fun with Excel, Python, C#"
  instagram = ""
  youtube = "https://www.youtube.com/channel/UCZpuwVWs-uvyZtgPRbLbxIg"
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-red"
  featured_image = "/images/gohugo-default-sample-hero-image.jpg"
  recent_posts_number = 2