baseURL = "http://kodindonesia.com/"
languageCode = "en-us"
title = "Kodindonesia"
theme = "ananke"

# https://www.youtube.com/feeds/videos.xml?channel_id=UCZpuwVWs-uvyZtgPRbLbxIg

DefaultContentLanguage = "en"


[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  favicon = ""
  site_logo = ""
  description = "Puzzles, games, ... fun with Excel, Python, C#"
  instagram = "https://instagram.com/kodindonesia?igshid=ki3ziaoyx4nd"
  youtube = "https://www.youtube.com/channel/UCZpuwVWs-uvyZtgPRbLbxIg"
  background_color_class = "bg-red"
  # featured_image = "/images/gohugo-default-sample-hero-image.jpg"
  recent_posts_number = 3